version: '3.8'

services:
    redis:
        image: redis:7-alpine
        container_name: Traffic-Guard-redis
        restart: always
        ports:
            - '6379:6379'
        command: >
            redis-server
            --save 60 1
            --loglevel notice
            --maxmemory 256mb
            --maxmemory-policy noeviction
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5

volumes:
    redis_data:
        driver: local
